file_uploads = On
upload_max_filesize = 10M
post_max_size = 10M
max_execution_time = 600

session.save_path = /tmp/
error_log = log/php-fpm.log
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED

[Date]
date.timezone = "America/Mexico_City"
